app:
  localization-properties:
    resource-urls:
      en: /questions-en.csv
      ru: /questions-ru.csv
    greeting: 'Укажите язык / Choice language'
    exit:
      - выйти
      - exit
    language:
      - рус
      - ru
      - en
spring:
  profiles:
    active: shell
---
spring:
  main:
    allow-circular-references: true
  shell:
    interactive:
      enabled: true
    command:
      history:
        enabled: false
      script:
        enabled: false
      stacktrace:
        enabled: false
  config:
    activate:
      on-profile: shell

---

spring:
  shell:
    interactive:
      enabled: false
  main:
    allow-circular-references: true
    banner-mode: off
  config:
    activate:
      on-profile: test

---

spring:
  main:
    allow-circular-references: true
  shell:
    interactive:
      enabled: false
  config:
    activate:
      on-profile: console